Build script updates
Rightpoint/android-template pull request #22
Opened 2018-08-17 18:33 UTC by jonduran3000

* Removed unnecessary beta track
* Updated the CircleCI script file
* Updated various dependencies

2018-08-17 23:23 UTC, octohub requested changes
Great work brother 💯 

All of my comments except one are nice to haves. If you could address them in this PR great. If not, please break them out into separate issues.

2018-08-17 23:23 UTC, octohub commented on {{ cookiecutter.repo_name }}/gradle/dependencies.gradle
> +buildConfig.minSdk      = 21
#pp I think this should be bumped to `23` as that seems to be the default we use. But this is really a broader conversation we should have internally.

2018-08-17 23:23 UTC, octohub commented on {{ cookiecutter.repo_name }}/gradle/dependencies.gradle
> +buildConfig.compileSdk  = 28
#nth While we're at it, in the `config.yml` generation please change the docker image from `- image: circleci/android:api-27-alpha` to `- image: circleci/android:api-28-alpha` and the sdkmanager from `sdkmanager "platform-tools" "platforms;android-27"` to `sdkmanager "platform-tools" "platforms;android-28"`.

2018-08-17 23:23 UTC, octohub commented on {{ cookiecutter.repo_name }}/app/build.gradle
> -        }
#req Update the `deploy.gradle` file by replacing `betaRelease` with `productionRelease`.

2018-08-17 23:23 UTC, octohub commented on {{ cookiecutter.repo_name }}/app/build.gradle
> -        }
#nth Not related to this PR explicitly, but please add a `.gitignore` file in the remote module that simply has `/build`. This is already in the other modules e.g. `domain` and `device`.

2018-08-17 23:23 UTC, octohub commented on {{ cookiecutter.repo_name }}/app/build.gradle
> -        }
#nth Add `/develop`, `/production`, and `/release` to the `.gitignore` in the `app` module to prevent generated builds and json from being committed.

2018-08-31 14:13 UTC, jonduran3000 commented on {{ cookiecutter.repo_name }}/gradle/dependencies.gradle
> +buildConfig.minSdk      = 21
API `23` is really the default?

2018-08-31 15:20 UTC, octohub commented on {{ cookiecutter.repo_name }}/gradle/dependencies.gradle
> +buildConfig.minSdk      = 21
Yes sir. For Android our SOWs default to the current version plus the last two versions. Just sent you a screenshot of the convo where I confirmed this with the bd team. I know it seems aggressive but the [distribution dashboard](https://developer.android.com/about/dashboards/) skews towards older API versions because it includes global stats. Most of our apps target the US market which is going to have more modern devices.

2018-08-31 15:22 UTC, octohub requested changes
Great work! I'll approve once the minSdkVersion is bumped

2018-08-31 16:01 UTC, octohub approved these changes
💯

2018-08-31 16:01 UTC, merged